name: PR CI

on:
  pull_request:

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Pull Request CI
    runs-on: ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Run tests"

      - name: Run Tests
        run: echo "Run tests"