name: PR CI

on:
  pull_request:

  workflow_run:
    workflows: ["Label when reviewed"]
    types: ['completed']

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Pull Request CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: "0"

      - name: Run Tests
        run: echo "Run tests"

      - name: Check Commit Message
        id: check_msg
        run: |
          set -xe pipefail
          echo "commitMsg=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo $commitMsg
