name: PR CI

on:
  pull_request_review:
    types: [submitted]

  workflow_run:
    workflows: ["Label when reviewed"]
    types: ['completed']

# Limit CI to cancel previous runs in the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Pull Request CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Run tests"
